name: website_mobile
description: Ganesha Energi Mobile App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  intl: ^0.19.0
  shimmer: ^3.0.0
  google_fonts: ^6.1.0
  file_picker: 10.0.0
  image: ^4.9.1
  url_launcher: ^6.2.0
  path_provider: ^2.1.0
  local_auth: ^3.0.1
  gal: ^2.3.0
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^18.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "#4F46E5"
  adaptive_icon_foreground: "assets/app_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
